version: '3.8'

services:
  events-board:
    container_name: events-board
    restart: on-failure
    build: .
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
      - /app/server/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - events-db

  events-db:
    container_name: events-db
    restart: always
    image: postgres:14
    ports:
      - 5432:5432
    env_file:
      - .env
