name: Deploy to Fly

on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app to Fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16.10"
          cache: "npm"

      - name: Install client packages
        run: npm ci --prefix client

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy events-board-app to Fly.io
        run: flyctl deploy --dockerfile ./dockerfile.prod --remote-only --no-cache

